version: "3.8"

services:
  rls_digital_twin:
    shm_size: '12gb'
    image: rls_digital_twin:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      DISPLAY: ${DISPLAY:-}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY:-}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR:-}
      PULSE_SERVER: ${PULSE_SERVER:-}
    ports:
      - "7007:7007"
    volumes:
      - ../:/workspace/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - $HOME/.Xauthority:/home/user/.Xauthority:rw
      - $HOME/.ssh:/home/user/.ssh:rw
    working_dir: /workspace/
    command: /bin/bash
