robot_base_frame: base_link

transform_tolerance: 0.5

robot_radius: 0.32 # 0.30
inflater:
  robot_radius: 0.32 #0.30
  inflation_radius: 0.35 # 0.30
  cost_scaling_factor: 10.0

# Obstacles are defined in robot folders
